export interface Question {
  id: number;
  subject: "english" | "math";
  difficulty: "easy" | "hard";
  text: string;
  choices: string[];
  answer: number;
}

export const questions: Question[] = [
  // ── EASY ENGLISH ─────────────────────────────────────────────────────────
  {
    id: 1,
    subject: "english",
    difficulty: "easy",
    text: "Which word is a synonym for 'brave'?",
    choices: ["Timid", "Courageous", "Careless", "Lazy"],
    answer: 1,
  },
  {
    id: 2,
    subject: "english",
    difficulty: "easy",
    text: "Choose the correct sentence:",
    choices: [
      "She don't like dragons.",
      "She doesn't likes dragons.",
      "She doesn't like dragons.",
      "She do not likes dragons.",
    ],
    answer: 2,
  },
  {
    id: 3,
    subject: "english",
    difficulty: "easy",
    text: "What is the plural of 'hero'?",
    choices: ["Heros", "Heroe", "Heroes", "Hereos"],
    answer: 2,
  },
  {
    id: 4,
    subject: "english",
    difficulty: "easy",
    text: "Which word is an antonym for 'victory'?",
    choices: ["Triumph", "Success", "Defeat", "Glory"],
    answer: 2,
  },
  {
    id: 5,
    subject: "english",
    difficulty: "easy",
    text: "Fill in the blank: The knight __ his sword at the dragon.",
    choices: ["rise", "raised", "risen", "rising"],
    answer: 1,
  },
  {
    id: 6,
    subject: "english",
    difficulty: "easy",
    text: "Which word means 'very large'?",
    choices: ["Tiny", "Faint", "Gigantic", "Slender"],
    answer: 2,
  },
  {
    id: 7,
    subject: "english",
    difficulty: "easy",
    text: "What part of speech is the word 'quickly'?",
    choices: ["Noun", "Verb", "Adjective", "Adverb"],
    answer: 3,
  },
  {
    id: 8,
    subject: "english",
    difficulty: "easy",
    text: "Choose the correctly spelled word:",
    choices: ["Recieve", "Believe", "Acheive", "Releive"],
    answer: 1,
  },
  {
    id: 9,
    subject: "english",
    difficulty: "easy",
    text: "The wizard cast a __ spell on the monster.",
    choices: ["power", "powerfull", "powerful", "powerfully"],
    answer: 2,
  },
  {
    id: 10,
    subject: "english",
    difficulty: "easy",
    text: "Which sentence uses correct punctuation?",
    choices: [
      "The dragon roared, and flames filled the sky.",
      "The dragon roared and, flames filled the sky.",
      "The dragon, roared and flames filled the sky.",
      "The dragon roared and flames, filled the sky.",
    ],
    answer: 0,
  },
  // ── EASY MATH ────────────────────────────────────────────────────────────
  {
    id: 11,
    subject: "math",
    difficulty: "easy",
    text: "What is 12 × 8?",
    choices: ["86", "96", "104", "112"],
    answer: 1,
  },
  {
    id: 12,
    subject: "math",
    difficulty: "easy",
    text: "Solve: 144 ÷ 12 = ?",
    choices: ["11", "13", "12", "14"],
    answer: 2,
  },
  {
    id: 13,
    subject: "math",
    difficulty: "easy",
    text: "What is 25% of 200?",
    choices: ["25", "40", "50", "75"],
    answer: 2,
  },
  {
    id: 14,
    subject: "math",
    difficulty: "easy",
    text: "What is 7² (seven squared)?",
    choices: ["14", "42", "49", "56"],
    answer: 2,
  },
  {
    id: 15,
    subject: "math",
    difficulty: "easy",
    text: "Solve: 3/4 + 1/4 = ?",
    choices: ["4/8", "4/4", "2/4", "3/8"],
    answer: 1,
  },
  {
    id: 16,
    subject: "math",
    difficulty: "easy",
    text: "What is the area of a rectangle 6 × 9?",
    choices: ["54", "45", "36", "63"],
    answer: 0,
  },
  {
    id: 17,
    subject: "math",
    difficulty: "easy",
    text: "What is 15% of 80?",
    choices: ["10", "12", "15", "18"],
    answer: 1,
  },
  {
    id: 18,
    subject: "math",
    difficulty: "easy",
    text: "Solve: 256 − 128 = ?",
    choices: ["118", "124", "128", "132"],
    answer: 2,
  },
  {
    id: 19,
    subject: "math",
    difficulty: "easy",
    text: "What is the next prime number after 11?",
    choices: ["12", "13", "14", "15"],
    answer: 1,
  },
  {
    id: 20,
    subject: "math",
    difficulty: "easy",
    text: "If x + 7 = 15, what is x?",
    choices: ["6", "7", "8", "9"],
    answer: 2,
  },
  // ── HARD ENGLISH ─────────────────────────────────────────────────────────
  {
    id: 21,
    subject: "english",
    difficulty: "hard",
    text: "Which of the following is an example of personification?",
    choices: [
      "The stars danced playfully in the midnight sky.",
      "The wind howled through the empty forest.",
      "The car engine purred smoothly down the road.",
      "The leaves displayed vibrant colors in autumn.",
    ],
    answer: 0,
  },
  {
    id: 22,
    subject: "english",
    difficulty: "hard",
    text: "Identify the subordinate clause: 'Although the knight was weary, he pressed on.'",
    choices: [
      "he pressed on",
      "the knight was weary",
      "Although the knight was weary",
      "pressed on",
    ],
    answer: 2,
  },
  {
    id: 23,
    subject: "english",
    difficulty: "hard",
    text: "Which sentence contains a dangling modifier?",
    choices: [
      "Running through the forest, the trees blurred past the hero.",
      "The dragon, exhausted from battle, slumped to the ground.",
      "After studying for hours, she finally understood the spell.",
      "Having lost his shield, the warrior retreated.",
    ],
    answer: 0,
  },
  {
    id: 24,
    subject: "english",
    difficulty: "hard",
    text: "What does the word 'ephemeral' mean?",
    choices: ["Eternal and lasting", "Lasting a very short time", "Deeply mysterious", "Extremely powerful"],
    answer: 1,
  },
  {
    id: 25,
    subject: "english",
    difficulty: "hard",
    text: "Choose the sentence in the subjunctive mood:",
    choices: [
      "He fights the dragon every night.",
      "If he were a dragon, he would breathe fire.",
      "She has defeated many monsters.",
      "The wizard cast three spells.",
    ],
    answer: 1,
  },
  {
    id: 26,
    subject: "english",
    difficulty: "hard",
    text: "Which figure of speech is used in: 'The pen is mightier than the sword'?",
    choices: ["Simile", "Alliteration", "Metonymy", "Onomatopoeia"],
    answer: 2,
  },
  {
    id: 27,
    subject: "english",
    difficulty: "hard",
    text: "Identify the type of irony: A fire station burns down.",
    choices: ["Dramatic irony", "Verbal irony", "Situational irony", "Cosmic irony"],
    answer: 2,
  },
  {
    id: 28,
    subject: "english",
    difficulty: "hard",
    text: "Which word correctly completes the sentence: 'The council had __ opinions on the matter.'",
    choices: ["diverse", "divers", "diversion", "diverted"],
    answer: 0,
  },
  {
    id: 29,
    subject: "english",
    difficulty: "hard",
    text: "What is the term for the main opposing force in a story?",
    choices: ["Protagonist", "Narrator", "Antagonist", "Foil"],
    answer: 2,
  },
  {
    id: 30,
    subject: "english",
    difficulty: "hard",
    text: "In grammar, what is an 'appositive'?",
    choices: [
      "A verb that describes state of being",
      "A noun or phrase that renames the noun beside it",
      "An adjective that follows the noun",
      "A conjunction joining two clauses",
    ],
    answer: 1,
  },
  // ── HARD MATH ────────────────────────────────────────────────────────────
  {
    id: 31,
    subject: "math",
    difficulty: "hard",
    text: "Solve: 3x² − 12 = 0. What is x?",
    choices: ["±1", "±2", "±3", "±4"],
    answer: 1,
  },
  {
    id: 32,
    subject: "math",
    difficulty: "hard",
    text: "What is the value of log₂(64)?",
    choices: ["4", "5", "6", "8"],
    answer: 2,
  },
  {
    id: 33,
    subject: "math",
    difficulty: "hard",
    text: "A triangle has sides 5, 12, and 13. What type is it?",
    choices: ["Equilateral", "Isosceles", "Right", "Obtuse"],
    answer: 2,
  },
  {
    id: 34,
    subject: "math",
    difficulty: "hard",
    text: "What is the sum of interior angles in a hexagon?",
    choices: ["540°", "630°", "720°", "810°"],
    answer: 2,
  },
  {
    id: 35,
    subject: "math",
    difficulty: "hard",
    text: "If f(x) = 2x + 3, what is f(f(2))?",
    choices: ["13", "14", "17", "21"],
    answer: 2,
  },
  {
    id: 36,
    subject: "math",
    difficulty: "hard",
    text: "Simplify: (x² − 9) ÷ (x − 3)",
    choices: ["x − 3", "x + 3", "x² + 3", "x − 9"],
    answer: 1,
  },
  {
    id: 37,
    subject: "math",
    difficulty: "hard",
    text: "What is 3! + 4! (factorial)?",
    choices: ["24", "30", "36", "42"],
    answer: 1,
  },
  {
    id: 38,
    subject: "math",
    difficulty: "hard",
    text: "A circle has radius 7. What is its area? (Use π ≈ 3.14)",
    choices: ["43.96", "153.86", "49π", "21.98"],
    answer: 1,
  },
  {
    id: 39,
    subject: "math",
    difficulty: "hard",
    text: "What is the slope of a line perpendicular to y = 2x + 5?",
    choices: ["2", "−2", "1/2", "−1/2"],
    answer: 3,
  },
  {
    id: 40,
    subject: "math",
    difficulty: "hard",
    text: "Evaluate: ∑ (n=1 to 4) of n² = ?",
    choices: ["20", "25", "30", "36"],
    answer: 2,
  },
];
